# Mapping of volumes to their final chapters. A chapter's volume, if it has one, is the first key in this mapping
# whose value is greater than or equal to the chapter's number.
1 = 8
2 = 17
3 = 26
4 = 35
5 = 44
6 = 53
7 = 62
8 = 71
9 = 81
10 = 90
11 = 99
12 = 108
13 = 117
14 = 126
15 = 136
16 = 145
17 = 155
18 = 166
19 = 176
20 = 186
21 = 195
22 = 205
23 = 216
24 = 226
25 = 236
26 = 246
27 = 255
28 = 264
29 = 275
30 = 285
31 = 295
32 = 305
33 = 316
34 = 327
35 = 336
36 = 346
37 = 357
38 = 367
39 = 377
40 = 388
41 = 399
42 = 409
43 = 419
44 = 430
45 = 440
46 = 449
47 = 459
48 = 470
49 = 481
50 = 491
51 = 502
52 = 512
53 = 522
54 = 533
55 = 541
56 = 551
57 = 562
58 = 573
59 = 584
60 = 594
61 = 603
62 = 614
63 = 626
64 = 636
65 = 646
66 = 656
67 = 667
68 = 678
69 = 690
70 = 700
71 = 711
72 = 721
73 = 731
74 = 742
75 = 752
76 = 763
77 = 775
78 = 785
79 = 795
80 = 806
81 = 816
82 = 827
83 = 838
84 = 848
85 = 858
86 = 869
87 = 879
88 = 889
89 = 900
90 = 910
91 = 921
92 = 931
93 = 942
94 = 953
95 = 964
96 = 974
97 = 984
98 = 994
99 = 1004
100 = 1015
101 = 1025
102 = 1035
103 = 1046
104 = 1055
105 = 1065
106 = 1076
107 = 1088
108 = 1100
109 = 1110
110 = 1121
111 = 1133